<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width"/><meta charSet="utf-8"/><meta property="og:title" content="Python3 Protobuf Import Error"/><meta property="og:site_name" content="George Prichard&#x27;s blog"/><meta property="og:description"/><meta property="og:image"/><meta name="next-head-count" content="6"/><link rel="preload" href="/_next/static/css/7bf527c5fc874cac.css" as="style"/><link rel="stylesheet" href="/_next/static/css/7bf527c5fc874cac.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script src="/_next/static/chunks/webpack-cb7634a8b6194820.js" defer=""></script><script src="/_next/static/chunks/framework-5f4595e5518b5600.js" defer=""></script><script src="/_next/static/chunks/main-7c9e8fd8226b6573.js" defer=""></script><script src="/_next/static/chunks/pages/_app-c91b8fdce06a16b2.js" defer=""></script><script src="/_next/static/chunks/977-d02d6b0b927a7604.js" defer=""></script><script src="/_next/static/chunks/pages/blog/python-protobuf-import-error-7be2c33bff61917a.js" defer=""></script><script src="/_next/static/ZclvydqtvsqT0A5lN0nfL/_buildManifest.js" defer=""></script><script src="/_next/static/ZclvydqtvsqT0A5lN0nfL/_ssgManifest.js" defer=""></script><script src="/_next/static/ZclvydqtvsqT0A5lN0nfL/_middlewareManifest.js" defer=""></script></head><body><div id="__next" data-reactroot=""><div class="navbar"><div class="flex-1"><a class="btn btn-ghost normal-case text-xl" href="/">George Prichard</a></div><div class="flex-none"><ul class="menu menu-horizontal p-0"><li><a href="/blog">Blog</a></li></ul></div></div><div class="prose lg:prose-lg mx-auto px-4 py-8"><h1>Python 3 error</h1><p>I&#x27;m trying to make the switch to Python 3 at the moment, and was getting incredibly frustrated getting this error when I imported a module using Google&#x27;s Protocol Buffers:</p><pre><code class="language-python" parentName="pre">Traceback (most recent call last):
  File &quot;/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr
otobuf/internal/python_message.py&quot;, line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File &quot;/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr
otobuf/internal/python_message.py&quot;, line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File &quot;/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr
otobuf/internal/decoder.py&quot;, line 181, in ReadTag
    while six.indexbytes(buffer, pos) &amp; 0x80:
TypeError: unsupported operand type(s) for &amp;: &#x27;str&#x27; and &#x27;int&#x27;
</code></pre><p>After much messing around and not finding a fix from google, it turns out I had the wrong version of protobuf installed. Very easy fix:</p><pre><code parentName="pre">pip3 uninstall protobuf &amp;&amp; pip3 install python3-protobuf
</code></pre><p>Hopefully this post helps someone solve the same problem.</p></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/blog/python-protobuf-import-error","query":{},"buildId":"ZclvydqtvsqT0A5lN0nfL","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>