<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/css/9826168d115cf6fb.css" as="style"/><link rel="stylesheet" href="/_next/static/css/9826168d115cf6fb.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-5cd94c89d3acac5f.js"></script><script src="/_next/static/chunks/webpack-3982ab13f1530c64.js" defer=""></script><script src="/_next/static/chunks/framework-fc97f3f1282ce3ed.js" defer=""></script><script src="/_next/static/chunks/main-f4ae3437c92c1efc.js" defer=""></script><script src="/_next/static/chunks/pages/_app-d486b909caea9e66.js" defer=""></script><script src="/_next/static/chunks/586-fc70be302fad1b1f.js" defer=""></script><script src="/_next/static/chunks/pages/blog/%5Bslug%5D-945720dc868c05e4.js" defer=""></script><script src="/_next/static/9G_uiA_ALqwfGD1V_WagL/_buildManifest.js" defer=""></script><script src="/_next/static/9G_uiA_ALqwfGD1V_WagL/_ssgManifest.js" defer=""></script><script src="/_next/static/9G_uiA_ALqwfGD1V_WagL/_middlewareManifest.js" defer=""></script></head><body><div id="__next"><div class="navbar"><div class="flex-1"><a class="btn btn-ghost normal-case text-xl" href="/">George Prichard</a></div><div class="flex-none"><ul class="menu menu-horizontal p-0"><li><a href="/blog">Blog</a></li></ul></div></div><div class="prose lg:prose-lg mx-auto px-4 py-8"><h1>Python3 Protobuf Import Error</h1><div><h1 id="python3error">Python 3 error</h1>
<p>I'm trying to make the switch to Python 3 at the moment, and was getting incredibly frustrated getting this error when I imported a module using Google's Protocol Buffers:</p>
<pre><code class="python language-python">Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr
otobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr
otobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr
otobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) &amp; 0x80:
TypeError: unsupported operand type(s) for &amp;: 'str' and 'int'
</code></pre>
<p>After much messing around and not finding a fix from google, it turns out I had the wrong version of protobuf installed. Very easy fix:</p>
<pre><code>pip3 uninstall protobuf &amp;&amp; pip3 install python3-protobuf
</code></pre>
<p>Hopefully this post helps someone solve the same problem.</p></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"meta":{"title":"Python3 Protobuf Import Error","date":"2017/01/02"},"content":"\u003ch1 id=\"python3error\"\u003ePython 3 error\u003c/h1\u003e\n\u003cp\u003eI'm trying to make the switch to Python 3 at the moment, and was getting incredibly frustrated getting this error when I imported a module using Google's Protocol Buffers:\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"python language-python\"\u003eTraceback (most recent call last):\n  File \"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr\notobuf/internal/python_message.py\", line 1087, in MergeFromString\n    if self._InternalParse(serialized, 0, length) != length:\n  File \"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr\notobuf/internal/python_message.py\", line 1109, in InternalParse\n    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)\n  File \"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/pr\notobuf/internal/decoder.py\", line 181, in ReadTag\n    while six.indexbytes(buffer, pos) \u0026amp; 0x80:\nTypeError: unsupported operand type(s) for \u0026amp;: 'str' and 'int'\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eAfter much messing around and not finding a fix from google, it turns out I had the wrong version of protobuf installed. Very easy fix:\u003c/p\u003e\n\u003cpre\u003e\u003ccode\u003epip3 uninstall protobuf \u0026amp;\u0026amp; pip3 install python3-protobuf\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eHopefully this post helps someone solve the same problem.\u003c/p\u003e"},"__N_SSG":true},"page":"/blog/[slug]","query":{"slug":"python-protobuf-import-error"},"buildId":"9G_uiA_ALqwfGD1V_WagL","isFallback":false,"gsp":true,"scriptLoader":[]}</script></body></html>